export const COLOR_PRIMARY_AMBER = "#EE760A";

export const COLOR_SECONDARY_BLACKY = "#1E1F26";

export const COLOR_SECONDARY_BLACKY_LIGHT = "#2C303A";

export const COLOR_SECONDARY_BLUE_DARKER = "#064CDA";
export const COLOR_SECONDARY_BLUE_LIGHTER = "#487BE5";
export const COLOR_PURPLE = "#d83550";
